improving_move((0,0), right).
improving_move((0,2), right).
improving_move((0,4), right).
improving_move((0,4), up).
improving_move((0,5), right).
improving_move((0,5), up).
improving_move((0,6), right).
improving_move((0,6), up).
improving_move((0,7), up).
improving_move((1,0), right).
improving_move((1,0), up).
improving_move((1,1), right).
improving_move((1,1), up).
improving_move((1,2), right).
improving_move((1,4), up).
improving_move((1,5), right).
improving_move((1,5), up).
improving_move((1,6), right).
improving_move((2,0), right).
improving_move((2,0), up).
improving_move((2,1), up).
improving_move((2,2), right).
improving_move((2,2), up).
improving_move((2,3), right).
improving_move((2,5), right).
improving_move((2,5), up).
improving_move((2,6), up).
improving_move((2,7), right).
improving_move((2,7), up).
improving_move((2,8), right).
improving_move((3,2), up).
improving_move((3,7), up).
improving_move((4,1), up).
improving_move((4,2), left).
improving_move((4,2), up).
improving_move((4,3), left).
improving_move((4,3), up).
improving_move((4,6), up).
improving_move((4,7), left).
improving_move((4,7), up).
improving_move((4,8), left).
improving_move((5,1), left).
improving_move((5,1), up).
improving_move((5,2), left).
improving_move((5,4), left).
improving_move((5,6), left).
improving_move((5,6), up).
improving_move((5,7), left).
improving_move((6,3), up).
improving_move((6,4), left).
improving_move((6,6), left).
improving_move((6,6), up).
improving_move((6,7), left).
improving_move((7,0), left).
improving_move((7,0), up).
improving_move((7,1), up).
improving_move((7,2), up).
improving_move((7,3), left).
improving_move((7,7), left).
improving_move((7,7), up).
improving_move((8,0), left).
improving_move((8,0), up).
improving_move((8,1), left).
improving_move((8,3), left).
improving_move((8,3), up).
improving_move((8,4), up).
improving_move((8,5), left).
improving_move((8,5), up).
improving_move((8,6), up).
improving_move((8,7), left).
